-- Create table for device heartbeats (PONG)
create table public.device_heartbeats (
  id bigint generated by default as identity primary key,
  device_id text default 'feeder_01',
  status text, -- OPEN/CLOSED
  distance int,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.device_heartbeats enable row level security;

-- Allow anonymous access
create policy "Enable all access" on public.device_heartbeats
for all using (true) with check (true);

-- Enable realtime
alter publication supabase_realtime add table public.device_heartbeats;
