-- Create a table for dashboard-to-device commands
create table public.device_commands (
  id bigint generated by default as identity primary key,
  command text not null,
  processed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.device_commands enable row level security;

-- Allow anonymous access (simplification for this prototype)
create policy "Enable all access for all users" on public.device_commands
for all using (true) with check (true);

-- Allow realtime subscription
alter publication supabase_realtime add table public.device_commands;
